var vocabCN = {
    "navbar_contact": "联系方式",
    "navbar_about": "关于我",
    "navbar_projects": "专案",
    "navbar_news": "新闻",
    "intro-lead-in": "自2013年开始编程。",
    "intro-heading": "不要评论坏代码。<br>重写它。<br>- Brian Kernighan",
    "button_about": "告诉我更多",
    "section_title_about": "关于我",
    "description_about": "我是德国开发人员。我出生于2002年，我是男性。<br>基本上，这就是我的工作：",
    "heading_java": "Java & C#",
    "description_java": "Java，JavaScript和Android开发",
    "heading_web_development": "网站开发",
    "description_web_development": "HTML和CSS设计（也是Web应用程序）",
    "heading_modding": "改装",
    "description_modding": "视频游戏的修改和补充",
    "heading_translations": "翻译",
    "description_translations": "我翻译英语，德语，西班牙语和意大利语之间。",
    "heading_brand": "品牌",
    "description_brand": "LPMG由两个主要分支组成:",
    "heading_brand_lpmg": "LPMG",
    "description_brand_lpmg": "品牌，设计，媒体，软件开发",
    "link_view_more": "查看更多",
    "heading_brand_lpmg_games": "LPMG Games | LPMG游戏开发",
    "description_brand_lpmg_games": "游戏开发和游戏设计",
    "heading_skills": "能力",
    "heading_projects": "最新项目",
    "heading_project_1": "Better Windows Mod",
    "title_project_1": "星露谷物语 | C#",
    "description_project_1": "此修改更改了星露谷物语中窗口的基本外观",
    "description_stats_years": "年的编程经验",
    "description_stats_reliability": "百分的可靠性",
    "description_stats_projects": "个项目",
    "description_stats_favorite_number": "是我最喜欢的数字",
    "header_bulletin_board": "布告板",
    "header_contact": "联系我",
    "header_media": "媒体",
    "header_working_hours": "工作时间",
    "tab_branding": "品牌推广",
    "tab_design": "设计",
    "tab_media": "媒体",
    "tab_development": "软件开发",
    "description_brand_lpmg_detail": "主要分支，负责通用软件开发和媒体开发",
    "tab_game_development": "游戏开发",
    "tab_game_design": "游戏设计",
    "description_brand_lpmg_games_detail": "二级分支，负责游戏开发和设计",
    "button_close": "停止",
    "button_close_2": "停止",
    "heading_project_2": "Premium Tea Shop",
    "title_project_2": "打字稿| HTML | CSS",
    "description_project_2": "Angular网上商店示例",
    "description_working_hours": "我现在真的没有做很多，因为学校"
}
