var vocabEN = {
    "navbar_contact": "Contact",
    "navbar_about": "About",
    "navbar_news": "News",
    "intro-lead-in": "Coding since 2013.",
    "intro-heading": "Don't comment bad code.<br>Rewrite it.<br>- Brian Kernighan",
    "button_about": "Tell Me More",
    "section_title_about": "ABOUT",
    "description_about": "I´m a german developer, born in 2002 and male! <br>Basically, thats what I do:",
    "heading_java": "Java & C#",
    "description_java": "Java, JavaScript and Android development",
    "heading_web_development": "Web Development",
    "description_web_development": "HTML and CSS design(also WebApplications)",
    "heading_modding": "Modding",
    "description_modding": "Mods and additions to video games",
    "heading_translations": "Translations",
    "description_translations": "I translate between English, German, Spanish and Italian.",
    "heading_brand": "The Brand",
    "description_brand": "LPMG consists of two mayor branches:",
    "heading_brand_lpmg": "LPMG",
    "description_brand_lpmg": "Branding, Design, Media, Software Development",
    "link_view_more": "View more",
    "heading_brand_lpmg_games": "LPMG Games",
    "description_brand_lpmg_games": "Game Development & Design",
    "heading_skills": "Skills",
    "heading_projects": "Latest Projects",
    "heading_project_1": "Better Windows Mod",
    "title_project_1": "Stardew Valley | C#",
    "description_project_1": "This mod changes the basic look of windows in Stardew Valley.",
    "description_stats_years": "Years of coding experience",
    "description_stats_reliability": "% reliability",
    "description_stats_projects": "projects",
    "description_stats_favorite_number": "is my favorite number",
    "header_bulletin_board": "Bulletin Board",
    "header_contact": "Contact",
    "header_media": "Media",
    "header_working_hours": "Working Hours",
    "tab_branding": "Branding",
    "tab_design": "Design",
    "tab_media": "Media",
    "tab_development": "Software Development",
    "description_brand_lpmg_detail": "Main branch, responsible for general development and media",
    "tab_game_development": "Game Development",
    "tab_game_design": "Game Design",
    "description_brand_lpmg_games_detail": "Secondary branch, responsible for game devopment and design",
    "button_close": "Close",
    "heading_project_2": "Premium Tea Shop",
    "title_project_2": "TypeScript | HTML | CSS",
    "description_project_2": "Angular test shop.",
    "description_working_hours": "I´m not really doing much at the moment because of school"
}
