var vocabJP = {
    "navbar_contact": "連絡先",
    "navbar_about": "情報",
    "navbar_projects": "プロジェクト",
    "navbar_news": "ニュース",
    "intro-lead-in": "2013年以降のプログラミング",
    "intro-heading": "悪いコードにはコメントしない。<br>それを書き換える。<br>- Brian Kernighan",
    "button_about": "もっと教えて",
    "section_title_about": "私について",
    "description_about": "私はドイツの開発者で、2002年に生まれ、男性です！ <br>基本的に、それが私がやっていることです：",
    "heading_java": "Java & C#",
    "description_java": "Java、JavaScriptおよびアンドロイド開発",
    "heading_web_development": "ウェブ開発",
    "description_web_development": "HTMLおよびCSSデザイン（Webアプリケーションも）",
    "heading_modding": "プログラム修正",
    "description_modding": "ビデオゲームへの改造と追加",
    "heading_translations": "翻訳",
    "description_translations": "英語、ドイツ語、スペイン語、イタリア語間の翻訳を準備しています",
    "heading_brand": "ブランド",
    "description_brand": "LPMGは2つの主要なブランチで構成されています。",
    "heading_brand_lpmg": "LPMG",
    "description_brand_lpmg": "ブランディング、デザイン、メディア、ソフトウェア開発",
    "link_view_more": "もっと見る",
    "heading_brand_lpmg_games": "LPMG Game Studios",
    "description_brand_lpmg_games": "ゲーム開発およびゲーム設計",
    "heading_skills": "スキル",
    "heading_projects": "最新のプロジェクト",
    "heading_project_1": "Better Windows Mod",
    "title_project_1": "Stardew Valley | C#",
    "description_project_1": "この変形は、Stardew Valleyのウィンドウの基本的な外観を変更します。",
    "description_stats_years": "年のコーディング経験",
    "description_stats_reliability": "％の信頼性",
    "description_stats_projects": "案件",
    "description_stats_favorite_number": "私の好きな番号",
    "header_bulletin_board": "掲示板",
    "header_contact": "連絡先",
    "header_media": "メディア",
    "header_working_hours": "労働時間",
    "tab_branding": "ブランディング",
    "tab_design": "設計",
    "tab_media": "メディア",
    "tab_development": "ソフトウェア開発",
    "description_brand_lpmg_detail": "メインブランチ、一般的なソフトウェア開発とメディアを担当",
    "tab_game_development": "ゲーム開発",
    "tab_game_design": "ゲームデザイン",
    "description_brand_lpmg_games_detail": "ゲームの開発と設計を担当するセカンダリブランチ",
    "button_close": "閉じる",
    "button_close_2": "閉じる",
    "heading_project_2": "Premium Tea Shop",
    "title_project_2": "TypeScript | HTML | CSS",
    "description_project_2": "Angular オンラインショップの例",
    "description_working_hours": "学校のせいで今はあまりやっていない",
    "heading_project_3": "GameHub",
    "title_project_3": "Java",
    "description_project_3": "Javaで書かれたミニゲームを含むポータブルプログラム",
    "heading_project_4": "Jile",
    "title_project_4": "Java",
    "description_project_4": "シンプルで実験的な2Dピクセルアートゲーム"
}
