var vocabKR = {
    "navbar_contact": "연락",
    "navbar_about": "정보",
    "navbar_news": "뉴스",
    "intro-lead-in": "2013년부터 프로그래밍 중입니다.",
    "intro-heading": "잘못된 코드에 대해 언급하지 마십시오.<br>다시 쓰세요.<br>- Brian Kernighan",
    "button_about": "더 말해 주세요",
    "section_title_about": "나에 대한 정보",
    "description_about": "저는 2002년에 태어난 독일인 개발자이고 남자입니다! <br>이것이 제가 하는 일입니다:",
    "heading_java": "Java & C#",
    "description_java": "Java, JavaScript 및 Android 개발",
    "heading_web_development": "웹 개발",
    "description_web_development": "HTML 및 CSS 설계(WebApplications도 포함)",
    "heading_modding": "개조",
    "description_modding": "비디오 게임의 개조",
    "heading_translations": "번역",
    "description_translations": "저는 영어, 독일어, 스페인어, 이탈리아어를 번역합니다.",
    "heading_brand": "브랜드",
    "description_brand": "LPMG는 두 개의 분기로 구성된다:",
    "heading_brand_lpmg": "LPMG",
    "description_brand_lpmg": "브랜딩, 디자인, 미디어, 소프트웨어 개발",
    "link_view_more": "더 많은 기능",
    "heading_brand_lpmg_games": "LPMG Game Studios",
    "description_brand_lpmg_games": "게임 개발 & 게임 디자인",
    "heading_skills": "기술들",
    "heading_projects": "최신 프로젝트",
    "heading_project_1": "Better Windows Mod",
    "title_project_1": "스타듀밸리 | C#",
    "description_project_1": "이 개조는 스타듀 밸리의 창문의 기본 모양을 바꾼다.",
    "description_stats_years": "년간 코딩 경험을 쌓",
    "description_stats_reliability": "% 신뢰성",
    "description_stats_projects": "개 GitHub프로젝트",
    "description_stats_total_downloads": "총 다운로드",
    "header_bulletin_board": "게시판",
    "header_contact": "연락",
    "header_media": "메디아",
    "header_working_hours": "근무 시간",
    "tab_branding": "브랜딩",
    "tab_design": "디자인",
    "tab_media": "메디아",
    "tab_development": "소프트웨어 개발",
    "description_brand_lpmg_detail": "일반 소프트웨어 개발 및 미디어 담당",
    "tab_game_development": "게임 개발",
    "tab_game_design": "게임 디자인",
    "description_brand_lpmg_games_detail": "게임 개발 및 게임 디자인 담당",
    "button_close": "닫기",
    "heading_project_2": "Premium Tea Shop",
    "title_project_2": "TypeScript | HTML | CSS",
    "description_project_2": "Angular 온라인 상점 예",
    "description_working_hours": "저는 지금 학교 때문에 별로 많은 일을 하고 있지 않아요",
    "navbar_projects": "프로젝트",
    "heading_project_3": "GameHub",
    "title_project_3": "Java",
    "description_project_3": "Java로 작성된 미니 게임이 포함된 휴대용 프로그램",
    "heading_project_4": "Jile",
    "title_project_4": "Java",
    "description_project_4": "간단하고 실험적인 2D 픽셀 아트 게임",
    "button_close_2": "닫기"
}
